apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  role: karpenter-por-test
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: por-test
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: por-test
  tags:
    karpenter.sh/discovery: por-test