apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: ingress
spec:
  weight: 10
  disruption:
    consolidateAfter: 30s
    consolidationPolicy: WhenEmpty
  template:
    metadata:
      labels:
        ingress: "true"
    spec:
      kubelet:
        maxPods: 110
      nodeClassRef:
        name: default
      requirements:
      - key: "karpenter.k8s.aws/instance-category"
        operator: In
        values: ["c", "m", "r"]
      - key: "karpenter.k8s.aws/instance-generation"
        operator: Gt
        values: ["4"]
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot